export type GalleryCategory = "fleet" | "trips" | "events";

export const galleryCategories: { id: GalleryCategory; label: string }[] = [
  { id: "fleet", label: "Our Fleet" },
  { id: "trips", label: "Trips & Destinations" },
  { id: "events", label: "Events & Weddings" },
];

export type GalleryImage = {
  src: string;
  title: string;
  alt: string;
  category: GalleryCategory;
  /** Rotates a small set of aspect ratios to give the masonry grid rhythm. */
  aspect: "portrait" | "square" | "landscape";
};

// Drop new photos into /public/gallery and add an entry below, e.g.:
// { src: "/gallery/my-photo.jpg", title: "Short title", alt: "Describe the photo", category: "fleet", aspect: "landscape" },
export const galleryImages: GalleryImage[] = [
  {
    src: "/gallery/tigress-with-cubs-forest-clearing.jpg",
    title: "Tigress with Cubs on Safari",
    alt: "A tigress walking with two cubs through a forest clearing during a wildlife safari trip",
    category: "trips",
    aspect: "square",
  },
  {
    src: "/gallery/safari-tiger-and-cub-01.jpg",
    title: "Tiger Sighting on Safari",
    alt: "Tiger and cub spotted in the grass during a jungle safari trip organised by Renuka Tours & Travels",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/safari-jeep-tiger-sighting-01.jpg",
    title: "Safari Jeep Tiger Sighting",
    alt: "Tourists photographing a tiger from safari jeeps lined up on a forest trail",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/safari-jeep-tiger-sighting-03.jpg",
    title: "Tourists Photographing Tiger",
    alt: "Tourists in safari jeeps photographing a tiger walking near the tree line",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/safari-tiger-cub-walking-01.jpg",
    title: "Tiger Cub on the Move",
    alt: "A tiger and cub walking past a tree, seen from an open safari vehicle",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/indian-gaur-bison-forest-01.jpg",
    title: "Indian Gaur in the Wild",
    alt: "An Indian gaur (Indian bison) standing at the edge of a forest trail",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/indian-gaur-bison-forest-02.jpg",
    title: "Indian Gaur Close-Up",
    alt: "Close-up of an Indian gaur grazing among the trees on a wildlife safari",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/dense-forest-canopy-01.jpg",
    title: "Forest Canopy Trail",
    alt: "Dense green forest canopy along a wildlife safari trail",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/dense-forest-canopy-02.jpg",
    title: "Tall Trees on Safari Trail",
    alt: "Tall trees and undergrowth lining a forest safari trail",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/ooty-tea-garden-panorama-01.jpg",
    title: "Ooty Tea Garden Panorama",
    alt: "Panoramic view of rolling tea garden hills near Ooty under a cloudy sky",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/ooty-tea-garden-panorama-02.jpg",
    title: "Tea Gardens at Dusk",
    alt: "Tea garden hills near Ooty lit by evening light with dramatic clouds overhead",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/ooty-tea-garden-tall-trees-01.jpg",
    title: "Tea Estate Tree Line",
    alt: "Tall trees rising above rows of tea bushes on a hillside tea estate",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/ooty-tea-garden-tall-trees-02.jpg",
    title: "Tea Estate Hillside",
    alt: "A hillside tea estate with tall trees under an overcast sky",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/ghat-road-mountain-viewpoint-01.jpg",
    title: "Ghat Road Mountain View",
    alt: "Mountain range viewed from a hairpin bend on a hill-station ghat road",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/ghat-road-mountain-viewpoint-02.jpg",
    title: "Ghat Road Viewpoint",
    alt: "Scenic mountain viewpoint along a ghat road with crash barriers in the foreground",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/ghat-road-mountain-viewpoint-03.jpg",
    title: "Hills Along the Ghat Road",
    alt: "Layered green hills viewed from a curve on a hill-station ghat road",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/foggy-hill-road-01.jpg",
    title: "Misty Hill Road",
    alt: "A tour vehicle driving along a misty hill road wrapped in fog",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/foggy-hill-road-02.jpg",
    title: "Foggy Mountain Pass",
    alt: "A bus ahead on a foggy mountain road during a hill-station trip",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/foggy-hillside-greenery-01.jpg",
    title: "Misty Hillside Greenery",
    alt: "Fog rolling over green hillside shrubs along a mountain road",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/coastal-resort-lawn-palms-01.jpg",
    title: "Palm-Lined Resort Lawn",
    alt: "A palm-lined lawn at a coastal resort with a children's play area in the background",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-lawn-palms-02.jpg",
    title: "Coastal Resort Grounds",
    alt: "Guests walking across a palm-shaded lawn at a coastal resort near the sea",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-lawn-palms-03.jpg",
    title: "Resort Lawn with Palms",
    alt: "A landscaped resort lawn with palm trees and a rock garden feature",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-walkway-01.jpg",
    title: "Palm-Fringed Beach Walkway",
    alt: "A stone walkway lined with palm trees leading towards the beach at a coastal resort",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-stone-ruin-01.jpg",
    title: "Resort Garden Folly",
    alt: "A stone ruin-style garden folly surrounded by palms and flowering shrubs at a coastal resort",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-palm-silhouette-dusk.jpg",
    title: "Palm Trees at Dusk",
    alt: "Silhouetted palm trees against the evening sky at a coastal resort",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-driftwood-art.jpg",
    title: "Driftwood Garden Feature",
    alt: "A driftwood sculpture surrounded by rocks and palms on a coastal resort lawn",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/coastal-resort-antique-bullock-cart.jpg",
    title: "Antique Bullock Cart Display",
    alt: "A restored antique wooden bullock cart displayed on a palm-shaded resort lawn",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/tirupati-rock-cliff-closeup.jpg",
    title: "Tirupati Rock Formation",
    alt: "Close-up of a rocky cliff face on the hills of Tirupati",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/tirupati-temple-entrance-01.jpg",
    title: "Tirupati Temple Approach",
    alt: "Buses and vehicles at the base of the Tirupati temple hills during a pilgrimage trip",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/tirupati-hills-temple-gopuram.jpg",
    title: "Tirupati Temple Gopuram",
    alt: "A distant temple gopuram framed between the rocky hills of Tirupati",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/tirupati-hilltop-cliff-windmill.jpg",
    title: "Tirupati Hilltop View",
    alt: "A rocky hilltop cliff near Tirupati with a wind turbine on the ridge",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/tempo-traveller-interior-seating.jpg",
    title: "Tempo Traveller Seating",
    alt: "Comfortable reclining seats inside a tempo traveller used on a group trip",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/tempo-traveller-exterior-view.jpg",
    title: "Tempo Traveller on the Road",
    alt: "A tempo traveller van parked on a group outstation trip",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/tirupati-temple-tour-vehicle.jpg",
    title: "Tour Vehicle at Tirupati",
    alt: "A garlanded tour vehicle parked in front of a temple gopuram during a Tirupati pilgrimage trip",
    category: "trips",
    aspect: "portrait",
  },
  {
    src: "/gallery/tour-coach-interior-seating.jpg",
    title: "Coach Interior Seating",
    alt: "Rows of covered seats inside a tourist coach used for a group trip",
    category: "trips",
    aspect: "landscape",
  },
  {
    src: "/gallery/tour-coach-exterior-view.jpg",
    title: "Tourist Coach on the Road",
    alt: "A tourist coach parked during a long-distance group trip",
    category: "trips",
    aspect: "landscape",
  },
];
